
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
        - name: chatbot-ui
          image: gauridocker777/devops:latest
          ports:
            - containerPort: 80
