apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui-service
spec:
  selector:
    app: chatbot-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Ensure the port matches with your application container port
      nodePort: 30080    # You can specify a custom NodePort or leave it for auto-assignment
  type: NodePort
